# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: JonW91.CLImate
PackageVersion: 0.1.0-beta
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: climate.exe
    PortableCommandAlias: climate
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/JonW91/CLImate/releases/download/v0.1.0-beta/climate-win-x64.zip
    InstallerSha256: PLACEHOLDER_SHA256_WINDOWS_X64
ManifestType: installer
ManifestVersion: 1.6.0
