# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json
PackageIdentifier: JonW91.CLImate
PackageVersion: 0.1.2
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
