# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: JonW91.CLImate
PackageVersion: 0.1.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: climate.exe
    PortableCommandAlias: climate
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/JonW91/CLImate/releases/download/v0.1.2/climate-win-x64.zip
    InstallerSha256: 1033fb1b2bbaf18fe02820081736b6c60742a289cf35470ffe61d8b51511435e
ManifestType: installer
ManifestVersion: 1.6.0
